import{a as b,S as L,i as n}from"./assets/vendor-C2ySes1p.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function m(r,t=1){return(await b.get("https://pixabay.com/api/",{params:{key:"55036225-8ce8ea9a0711c46d4e7453374",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const w=new L(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".load-more");function y(r){const t=document.querySelector(".gallery"),a=r.map(o=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${o.largeImageURL}">
        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p><b>Likes</b><br>${o.likes}</p>
        <p><b>Views</b><br>${o.views}</p>
        <p><b>Comments</b><br>${o.comments}</p>
        <p><b>Downloads</b><br>${o.downloads}</p>
      </div>
    </li>`).join("");t.insertAdjacentHTML("beforeend",a),w.refresh()}function S(){document.querySelector(".gallery").innerHTML=""}function p(){document.querySelector(".loader").classList.remove("is-hidden")}function g(){document.querySelector(".loader").classList.add("is-hidden")}function q(){f.classList.remove("is-hidden")}function u(){f.classList.add("is-hidden")}const v=document.querySelector(".form"),P=document.querySelector(".load-more");let c="",i=1,d=0;v.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.currentTarget.elements["search-text"].value.trim(),i=1,!c){n.warning({message:"Please enter a search term"});return}S(),u(),p();try{const t=await m(c,i);d=t.totalHits,d===0?n.error({message:"Sorry, no images found!"}):(y(t.hits),h())}catch(t){n.error({message:t.message})}finally{g(),r.target.reset()}});P.addEventListener("click",async()=>{i+=1,u(),p();try{const r=await m(c,i);y(r.hits);const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}h()}catch(r){n.error({message:r.message})}finally{g()}});function h(){i*15>=d?(u(),n.info({message:"We're sorry, but you've reached the end of search results."})):q()}
//# sourceMappingURL=index.js.map
